### ISSUE TITLE
White space with README generation when it should not have occurred

### ISSUE THREAD

**Issue by astrochun** [ualibraries/LD_Cool_P#117]
**Describe the bug (REQUIRED)**

Vaguely recalled an issue when I run the readme generation and there was extra white space in the Summary section

**Reproduction Steps (REQUIRED)**
This occurred for stage deposit #6859987

**Version information (please complete the following, default in brackets): (REQUIRED)**
 - LD_Cool-P version: 0.15.3
 - ReQUIAM branch info: master

**Expected behavior (Optional)**
The files are stored on the curation server under: 2.UnderReview/Chun_Ly_6859987

Logs are available in: prereq_script.2020-10-15.log

**Screenshots (Optional)**
The README.txt shows:
```
---------------------------------------------
## Summary

This is a curation test to examine handling of readme inspection. It should
generate one from the default template.

test this test with ReDATA team

extra text






---------------------------------------------
## Materials & Methods
```

**Additional context (Optional)**

**Comment by damian-romero** [comment]
Perhaps another fix that is required here **before** the empty space issue at the end of the summary field are the extra `\n` characters inserted in the `description` field from figshare.

Notice that I am not referring to the extra `\n\n` dealt with in:

```python
if readme_dict['description'][-2:] == "\n\n":
```

I am referring to extra `\n` characters inside the text itself where there should not be a new line character in the figshare description, which is the line break in:
```
This is a curation test to examine handling of readme inspection. It should
[LINE BREAK WHICH SHOULD NOT BE HERE]
generate one from the default template.
```

 These seem to be generated while retrieving data from figshare using `figshare.FigshareInstituteAdmin()` 

While inspecting the ReadmeClass, I found the following string output after converting from HTML to text in line 256:

```'This is a curation test to examine handling of readme inspection. It should\ngenerate one from the default template.\n\n```

To replicate use `update_readme_stage` with deposit `6859987` and insert a print after line `256`:
```python
        readme_dict['description'] = html2text(description)
        print(readme_dict)
```

**Comment by damian-romero** [comment]
Another issue: for handling newline charaters and empty spaces in the `summary` and `description` fields, I recommend using:

```python
readme_dict['description'].rstrip()
```

Instead of:

```python
if readme_dict['description'][-2:] == "\n\n":
    pass
```
I intend to refactor this code as such.

**Comment by damian-romero** [comment]
I haven't found the issue with the whitespace yet. I tried this method in the jinja template but did not solve the issue:

https://stackoverflow.com/questions/35775207/remove-unnecessary-whitespace-from-jinja-rendered-template

I will continue to investigate the problem.

**Comment by astrochun** [comment]
> Perhaps another fix that is required here **before** the empty space issue at the end of the summary field are the extra `\n` characters inserted in the `description` field from figshare.
> 
> Notice that I am not referring to the extra `\n\n` dealt with in:
> 
> ```python
> if readme_dict['description'][-2:] == "\n\n":
> ```
> 
> I am referring to extra `\n` characters inside the text itself where there should not be a new line character in the figshare description, which is the line break in:
> 
> ```
> This is a curation test to examine handling of readme inspection. It should
> [LINE BREAK WHICH SHOULD NOT BE HERE]
> generate one from the default template.
> ```
> 
> These seem to be generated while retrieving data from figshare using `figshare.FigshareInstituteAdmin()`
> 
> While inspecting the ReadmeClass, I found the following string output after converting from HTML to text in line 256:
> 
> `'This is a curation test to examine handling of readme inspection. It should\ngenerate one from the default template.\n\n`
> 
> To replicate use `update_readme_stage` with deposit `6859987` and insert a print after line `256`:
> 
> ```python
>         readme_dict['description'] = html2text(description)
>         print(readme_dict)
> ```

Regarding the \n in the description, this is from carriage returns in the description. Namely if someone wants to have separate paragraphs, we should respect that.

The .rstrip() may work, but not entirely sure until we have additional testing.

**Comment by astrochun** [comment]
> I haven't found the issue with the whitespace after the `summary` field yet. I tried this method in the jinja template but did not solve the problem:
> 
> https://stackoverflow.com/questions/35775207/remove-unnecessary-whitespace-from-jinja-rendered-template
> 
> I will continue to investigate.

I don't think the issue is in jinja. It's in the `ReadmeClass` I believe.

**Comment by damian-romero** [comment]
> > I haven't found the issue with the whitespace after the `summary` field yet. I tried this method in the jinja template but did not solve the problem:
> > https://stackoverflow.com/questions/35775207/remove-unnecessary-whitespace-from-jinja-rendered-template
> > I will continue to investigate.
> 
> I don't think the issue is in jinja template. It's in the `ReadmeClass` I believe.

Question:

Is the new space inside the description below intended? Because when I inspected the deposit on stage it doesn't look like it was intended:

```
'This is a curation test to examine handling of readme inspection. It should\ngenerate one from the default template.\n\n
```

If it was then no refactoring is needed, but if it wasn't then we may want to find a solution for those too.

**Comment by astrochun** [comment]
> > > I haven't found the issue with the whitespace after the `summary` field yet. I tried this method in the jinja template but did not solve the problem:
> > > https://stackoverflow.com/questions/35775207/remove-unnecessary-whitespace-from-jinja-rendered-template
> > > I will continue to investigate.
> > 
> > 
> > I don't think the issue is in jinja template. It's in the `ReadmeClass` I believe.
> 
> Question:
> 
> Is the new space inside the description below intended? Because when I inspected the deposit on stage it doesn't look like it was intended:
> 
> ```
> 'This is a curation test to examine handling of readme inspection. It should\ngenerate one from the default template.\n\n
> ```
> 
> If it was then no refactoring is needed, but if it wasn't then we may want to find a solution for those too.

The HTML to text also limits to 80 characters wide, which is why you see those `\n`

**Comment by damian-romero** [comment]
> > > > I haven't found the issue with the whitespace after the `summary` field yet. I tried this method in the jinja template but did not solve the problem:
> > > > https://stackoverflow.com/questions/35775207/remove-unnecessary-whitespace-from-jinja-rendered-template
> > > > I will continue to investigate.
> > > 
> > > 
> > > I don't think the issue is in jinja template. It's in the `ReadmeClass` I believe.
> > 
> > 
> > Question:
> > Is the new space inside the description below intended? Because when I inspected the deposit on stage it doesn't look like it was intended:
> > ```
> > 'This is a curation test to examine handling of readme inspection. It should\ngenerate one from the default template.\n\n
> > ```
> > 
> > 
> > If it was then no refactoring is needed, but if it wasn't then we may want to find a solution for those too.
> 
> The HTML to text also limits to 80 characters wide, which is why you see those `\n`

Makes sense. Do we want to get rid of those extra `\n` or should we keep them?

**Comment by damian-romero** [comment]
I found the issue with the extra spacing. It was a nesting bug in the if statements in the jinja2 template when a section is left empty. The if statement created three new lines even though the section was empty:

```html
{% if qualtrics_dict.files != 'nan' %}
---------------------------------------------
## Files and Folders

{{ qualtrics_dict.files }}
{% endif %} <!-- BUG: The block below will execute even when qualtrics_dict.files == 'nan' -->
{% if ( (qualtrics_dict.materials != 'nan') or
        (qualtrics_dict.contrib != 'nan') or
        (qualtrics_dict.notes != 'nan') or
        (figshare_dict.references != []) ) %}



{% endif %}
```

The fix below applies to this and the two sections below it (3 total)

```html
{% if qualtrics_dict.files != 'nan' %}
---------------------------------------------
## Files and Folders

{{ qualtrics_dict.files }}
{% if ( (qualtrics_dict.materials != 'nan') or
        (qualtrics_dict.contrib != 'nan') or
        (qualtrics_dict.notes != 'nan') or
        (figshare_dict.references != []) ) %}



{% endif %} <!-- Now the block only executes when qualtrics_dict.files != 'nan' -->
{% endif %}
```

**Comment by astrochun** [comment]
I would need to experiment to make sure. Feel free to commit the code. One of the reasons the `jinja2` template was done as such was to make sure that there where no whitespaces after Files and Folders if Materials, Contributors, Notes, and References were not available.

The best way I have found to test things is to replace the empty rows with A, B, C to see where it's coming from.
