### ISSUE TITLE
Bug: convenience scripts only work from the codes/LD_CoolP folder

### ISSUE THREAD

**Issue by zoidy** [ualibraries/LD_Cool_P#124]
The convenience scripts (move_next, get_pending, etc.) only work from the ~/codes/LD_Cool_P folder in the curator account on thel curation server. When working elsewhere, it is a bit inconvenient to have to return to the folder to execute a command. For convenience, the commands should be runnable globally

**Comment by astrochun** [comment]
Thanks for bringing this up.  Those scripts are in fact bash aliases and separate from the codebase.  As such, I'm creating an internal issue on our private kanban board that we use for cloud infrastructure and code deployment.

This issue will be closed.

**Comment by astrochun** [comment]
I should add that caution may be needed in running `move_next` within the folder of interest
