### ISSUE TITLE
Long Qualtrics links a problem for Outlook

### ISSUE THREAD

**Issue by astrochun** [ualibraries/LD_Cool_P#144]
**Describe the bug (REQUIRED)**
Links for the Qualtrics README are encoded to contain content. However, it seems that some of these links can be very long. @zoidy reported an issue that two deposits were too long that Outlook truncated the link.

**Reproduction Steps (REQUIRED)**
It appears that links don't work on Windows. It works for macOS and OWA. Not sure how Damian managed to send the email as I was not able to provide a very long link.

**Outputted Messages (REQUIRED)**
Provide the full message log if possible or a subset that includes a few lines before the failure:

**Version information (please complete the following, default in brackets): (REQUIRED)**
 - LD_Cool-P version: [e.g. `0.13.0`] 
 - ReQUIAM branch info: [e.g., `release/v0.13.0`]
 - `pandas` version: [e.g., 1.0.2]
 - `requests` version: [e.g., 2.22.0]
 - `numpy` version: [e.g., 1.17.4]
 - `jinja2` version: [e.g., 2.11.2]

**Expected behavior (Optional)**

**Screenshots (Optional)**

**Additional context (Optional)**
There is no native way to shorten Qualtrics links. Everyone on Qualtrics recommends a URL shortener. See for example: [https://libguides.library.kent.edu/qualtrics/shorter-links](https://libguides.library.kent.edu/qualtrics/shorter-links)

This will be implemented in `feature/144_url_shorten`

**Comment by astrochun** [comment]
I examined the issue for two deposits and they were 2213 and 3673 in length.

I found this [blog](https://softwareas.com/the-url-shortener-as-a-cloud-database/) that discuss URL shortener. It seems that TinyURL is the only one that we can consider using.

**Comment by damian-romero** [comment]
For the Qualtrics links, what I did was to send those over Google Chrome. I didn't run into any issues.

**Comment by astrochun** [comment]
> For the Qualtrics links, what I did was to send those over Google Chrome. I didn't run into any issues.

We had thought so since it seems that Microsoft Outlook on MacOS and Windows fails in certain circumstances.

**Comment by astrochun** [comment]
I also looked at Qualtrics API to see if there's a way to do personal links. Though I don't think this can include the level of embedded data that we want, so I'm fairly sure a URL shortener is the way to go.
