### ISSUE TITLE
Enhancement: Add CI testing for Python 3.9

### ISSUE THREAD

**Issue by damian-romero** [ualibraries/LD_Cool_P#155]
**Summary**
For future enhancements including typing checks, we should include CI for Python 3.9.

**Objectives**

Eventually take advantage of Python [3.9 typing features](https://docs.python.org/3/whatsnew/3.9.html)

**Proposal**

Modify `python-package.yml` to include Python 3.9.

*Testing notes*

*Additional notes*

On REQUIAM, we had to bump Pandas version to 1.2.1 as well as Numpy. See [this PR](https://github.com/ualibraries/ReQUIAM/pull/125).

**Implemented in**: 155_ci_testing_python_3_9

**Comment by astrochun** [comment]
Note: We can remove `3.7.5` since we have 3.7 (which is 3.7.9)
